version: '3.8'

services:
  coordinator_primary:
    build: .
    container_name: citus_coordinator_primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/docker-entrypoint-initdb.d/primary-entrypoint.sh"]
    volumes:
      - citus_primary_data:/var/lib/postgresql/data
      - ./primary-entrypoint.sh:/docker-entrypoint-initdb.d/primary-entrypoint.sh
    networks:
      - citus_network

  coordinator_standby:
    build: .
    container_name: citus_coordinator_standby
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/docker-entrypoint-initdb.d/standby-entrypoint.sh"]
    volumes:
      - citus_standby_data:/var/lib/postgresql/data
      - ./standby-entrypoint.sh:/docker-entrypoint-initdb.d/standby-entrypoint.sh
    depends_on:
      - coordinator_primary
    networks:
      - citus_network

  worker1:
    build: .
    container_name: citus_worker1
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    command: ["postgres", "-c", "wal_level=logical", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    volumes:
      - ./worker-pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker2:
    build: .
    container_name: citus_worker2
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    command: ["postgres", "-c", "wal_level=logical", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    volumes:
      - ./worker-pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker3:
    build: .
    container_name: citus_worker3
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    command: ["postgres", "-c", "wal_level=logical", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    volumes:
      - ./worker-pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  manager:
    build: .
    container_name: citus_manager
    depends_on:
      - coordinator_primary
      - coordinator_standby
      - worker1
      - worker2
      - worker3
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/setup.sh"]
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
    networks:
      - citus_network

networks:
  citus_network:
    driver: bridge

volumes:
  citus_primary_data:
  citus_standby_data:
