
services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    container_name: citus_loadbalancer
    ports:
      - "5432:5432"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      coordinator_primary:
        condition: service_healthy
      coordinator_secondary:
        condition: service_healthy
    networks:
      - citus_network
    restart: unless-stopped

  coordinator_primary:
    build: .
    container_name: citus_coordinator_primary
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/primary-entrypoint.sh"]
    volumes:
      - citus_primary_data:/var/lib/postgresql/data
      - ./primary-entrypoint.sh:/docker-entrypoint-initdb.d/primary-entrypoint.sh
    networks:
      - citus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  coordinator_secondary:
    build: .
    container_name: citus_coordinator_secondary
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/secondary-entrypoint.sh"]
    volumes:
      - citus_secondary_data:/var/lib/postgresql/data
      - ./secondary-entrypoint.sh:/docker-entrypoint-initdb.d/secondary-entrypoint.sh
    depends_on:
      coordinator_primary:
        condition: service_healthy
    networks:
      - citus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  worker1_primary:
    build: .
    container_name: citus_worker1_primary
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-primary-entrypoint.sh"]
    volumes:
      - worker1_primary_data:/var/lib/postgresql/data
      - ./worker-primary-entrypoint.sh:/docker-entrypoint-initdb.d/worker-primary-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker1_secondary:
    build: .
    container_name: citus_worker1_secondary
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
      PRIMARY_HOST: worker1_primary
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh"]
    volumes:
      - ./worker-standby-entrypoint.sh:/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh
      - worker1_secondary_data:/var/lib/postgresql/data
    depends_on:
      worker1_primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker2_primary:
    build: .
    container_name: citus_worker2_primary
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-primary-entrypoint.sh"]
    volumes:
      - worker2_primary_data:/var/lib/postgresql/data
      - ./worker-primary-entrypoint.sh:/docker-entrypoint-initdb.d/worker-primary-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker2_secondary:
    build: .
    container_name: citus_worker2_secondary
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
      PRIMARY_HOST: worker2_primary
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh"]
    volumes:
      - ./worker-standby-entrypoint.sh:/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh
      - worker2_secondary_data:/var/lib/postgresql/data
    depends_on:
      worker2_primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker3_primary:
    build: .
    container_name: citus_worker3_primary
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-primary-entrypoint.sh"]
    volumes:
      - worker3_primary_data:/var/lib/postgresql/data
      - ./worker-primary-entrypoint.sh:/docker-entrypoint-initdb.d/worker-primary-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker3_secondary:
    build: .
    container_name: citus_worker3_secondary
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
      PRIMARY_HOST: worker3_primary
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh"]
    volumes:
      - ./worker-standby-entrypoint.sh:/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh
      - worker3_secondary_data:/var/lib/postgresql/data
    depends_on:
      worker3_primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker_monitor:
    build: .
    container_name: citus_worker_monitor
    depends_on:
      - coordinator_primary
      - worker1_primary
      - worker1_secondary
      - worker2_primary
      - worker2_secondary
      - worker3_primary
      - worker3_secondary
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-promotion.sh"]
    volumes:
      - ./worker-promotion.sh:/docker-entrypoint-initdb.d/worker-promotion.sh
    networks:
      - citus_network
    restart: unless-stopped

  manager:
    build: .
    container_name: citus_manager
    depends_on:
      - coordinator_primary
      - coordinator_secondary
      - worker1_primary
      - worker1_secondary
      - worker2_primary
      - worker2_secondary
      - worker3_primary
      - worker3_secondary
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/setup.sh"]
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
    networks:
      - citus_network

networks:
  citus_network:
    driver: bridge

volumes:
  citus_primary_data:
  citus_secondary_data:
  worker1_primary_data:
  worker1_secondary_data:
  worker2_primary_data:
  worker2_secondary_data:
  worker3_primary_data:
  worker3_secondary_data:
