version: '3.8'

services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    container_name: citus_loadbalancer
    ports:
      - "5432:5432"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      coordinator_primary:
        condition: service_healthy
      coordinator_secondary:
        condition: service_healthy
    networks:
      - citus_network
    restart: unless-stopped

  coordinator_primary:
    build: .
    container_name: citus_coordinator_primary
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/primary-entrypoint.sh"]
    volumes:
      - citus_primary_data:/var/lib/postgresql/data
      - ./primary-entrypoint.sh:/docker-entrypoint-initdb.d/primary-entrypoint.sh
    networks:
      - citus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  coordinator_secondary:
    build: .
    container_name: citus_coordinator_secondary
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/secondary-entrypoint.sh"]
    volumes:
      - citus_secondary_data:/var/lib/postgresql/data
      - ./secondary-entrypoint.sh:/docker-entrypoint-initdb.d/secondary-entrypoint.sh
    depends_on:
      coordinator_primary:
        condition: service_healthy
    networks:
      - citus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  worker1_master:
    build: .
    container_name: citus_worker1_master
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-master-entrypoint.sh"]
    volumes:
      - worker1_master_data:/var/lib/postgresql/data
      - ./worker-master-entrypoint.sh:/docker-entrypoint-initdb.d/worker-master-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker1_slave:
    build: .
    container_name: citus_worker1_slave
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
      MASTER_HOST: worker1_master
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh"]
    volumes:
      - ./worker-standby-entrypoint.sh:/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh
      - worker1_slave_data:/var/lib/postgresql/data
    depends_on:
      worker1_master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker2_master:
    build: .
    container_name: citus_worker2_master
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-master-entrypoint.sh"]
    volumes:
      - worker2_master_data:/var/lib/postgresql/data
      - ./worker-master-entrypoint.sh:/docker-entrypoint-initdb.d/worker-master-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker2_slave:
    build: .
    container_name: citus_worker2_slave
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
      MASTER_HOST: worker2_master
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh"]
    volumes:
      - ./worker-standby-entrypoint.sh:/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh
      - worker2_slave_data:/var/lib/postgresql/data
    depends_on:
      worker2_master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker3_master:
    build: .
    container_name: citus_worker3_master
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-master-entrypoint.sh"]
    volumes:
      - worker3_master_data:/var/lib/postgresql/data
      - ./worker-master-entrypoint.sh:/docker-entrypoint-initdb.d/worker-master-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker3_slave:
    build: .
    container_name: citus_worker3_slave
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
      MASTER_HOST: worker3_master
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh"]
    volumes:
      - ./worker-standby-entrypoint.sh:/docker-entrypoint-initdb.d/worker-standby-entrypoint.sh
      - worker3_slave_data:/var/lib/postgresql/data
    depends_on:
      worker3_master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citus"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - citus_network

  worker_monitor:
    build: .
    container_name: citus_worker_monitor
    depends_on:
      - coordinator_primary
      - worker1_master
      - worker1_slave
      - worker2_master
      - worker2_slave
      - worker3_master
      - worker3_slave
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/worker-promotion.sh"]
    volumes:
      - ./worker-promotion.sh:/docker-entrypoint-initdb.d/worker-promotion.sh
    networks:
      - citus_network
    restart: unless-stopped

  manager:
    build: .
    container_name: citus_manager
    depends_on:
      - coordinator_primary
      - coordinator_secondary
      - worker1_master
      - worker1_slave
      - worker2_master
      - worker2_slave
      - worker3_master
      - worker3_slave
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/setup.sh"]
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
    networks:
      - citus_network

networks:
  citus_network:
    driver: bridge

volumes:
  citus_primary_data:
  citus_secondary_data:
  worker1_master_data:
  worker1_slave_data:
  worker2_master_data:
  worker2_slave_data:
  worker3_master_data:
  worker3_slave_data:
